/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
/** an image box is a basic image container */
export class ImageWrapper {
  dimension(): Array<number>
}
/** Image loader provides several way to load images into ImageWrapper */
export class ImageLoader {
  /** Create a new image from a byte slice. Makes an educated guess about the image format */
  static autoGuess(buffer: Array<number>): ImageWrapper
  /** Create a new image from a byte slice. Assumes the image is a PNG */
  static fromPng(buffer: Array<number>): ImageWrapper
}
